--PROCEDIMIENTOS ALMACENADOS
CREATE PROCEDURE SP_CATEGORIAS_INSERT(
@CATEGORIA TINYINT,
@NOMBRE NVARCHAR(15)
)
AS
	BEGIN
		INSERT INTO CATEGORIAS(CATEGORIA,NOMBRE)
		VALUES (@CATEGORIA,@NOMBRE)
	END

GO
--
EXECUTE SP_CATEGORIAS_INSERT 46,'HELADOS'
-------
GO
--
CREATE PROC SP_CATEGORIAS_SELECT
AS
	SELECT * FROM Categorias

	--
	EXECUTE SP_CATEGORIAS_SELECT
----------------------
CREATE PROCEDURE SP_CATEGORIAS_UPDATE(
@CATEGORIA TINYINT,
@NOMBRE NVARCHAR(15)
)
AS
	BEGIN
		UPDATE Categorias 
		SET NOMBRE = @NOMBRE
		WHERE CATEGORIA = @CATEGORIA

	END
	EXECUTE SP_CATEGORIAS_UPDATE 45,'SACOS'
---
CREATE PROCEDURE SP_CATEGORIAS_DELETE(
@CATEGORIA TINYINT
)
AS
BEGIN
	DECLARE @IDARTICULO NVARCHAR(5)
	SET @IDARTICULO =(SELECT IdArticulo 
	FROM Articulos WHERE Categ = @CATEGORIA)

	UPDATE Articulos SET CATEG = 1
	WHERE IdArticulo =@IDARTICULO 
	--
	DELETE FROM CATEGORIAS
	WHERE Categoria = @CATEGORIA

END
	--
	EXECUTE SP_CATEGORIAS_DELETE 45
	
	SELECT * FROM Categorias